version: '3'

services:
  laraduck:
    image: samdevelopment/laraduck
    volumes:
      - .:/opt/app
    ports:
      - 8888:80
    networks:
      - nicknet

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: second_assignment
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 33067:3306
    networks:
      - nicknet

volumes:
  mysqldata:
    driver: local

networks:
  nicknet:
    driver: bridge
